sectors = {

    # 🔵 NIFTY MAIN
    "Nifty 50": [
        "RELIANCE.NS","TCS.NS","HDFCBANK.NS","ICICIBANK.NS","INFY.NS",
        "ITC.NS","SBIN.NS","LT.NS","BHARTIARTL.NS","KOTAKBANK.NS"
    ],

    # 🏦 BANK
    "Bank": [
        "SBIN.NS","HDFCBANK.NS","ICICIBANK.NS","AXISBANK.NS","KOTAKBANK.NS",
        "PNB.NS","IDFCFIRSTB.NS","FEDERALBNK.NS"
    ],

    # 🚗 AUTO
    "Auto": [
        "TATAMOTORS.NS","MARUTI.NS","M&M.NS","BAJAJ-AUTO.NS",
        "HEROMOTOCO.NS","ASHOKLEY.NS","EICHERMOT.NS"
    ],

    # 💻 IT
    "IT": [
        "TCS.NS","INFY.NS","WIPRO.NS","HCLTECH.NS","TECHM.NS"
    ],

    # 💊 PHARMA
    "Pharma": [
        "SUNPHARMA.NS","CIPLA.NS","DRREDDY.NS","DIVISLAB.NS"
    ],

    # 🔩 METAL
    "Metal": [
        "TATASTEEL.NS","JSWSTEEL.NS","HINDALCO.NS","JINDALSTEL.NS"
    ],

    # ⚡ ENERGY
    "Energy": [
        "RELIANCE.NS","ONGC.NS","NTPC.NS","POWERGRID.NS","ADANIGREEN.NS"
    ],

    # 🏗️ INFRA
    "Infra": [
        "LT.NS","ADANIPORTS.NS","GMRINFRA.NS","IRB.NS"
    ],

    # 🛒 FMCG
    "FMCG": [
        "ITC.NS","HINDUNILVR.NS","NESTLEIND.NS","DABUR.NS","BRITANNIA.NS"
    ],

    # 🏢 REALTY
    "Realty": [
        "DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS"
    ],

    # 🚀 NIFTY 500 (Top Liquid Large List)
    "Nifty 500": [
        "RELIANCE.NS","TCS.NS","HDFCBANK.NS","ICICIBANK.NS","INFY.NS",
        "ITC.NS","SBIN.NS","LT.NS","BHARTIARTL.NS","KOTAKBANK.NS",
        "AXISBANK.NS","ASIANPAINT.NS","MARUTI.NS","HCLTECH.NS",
        "WIPRO.NS","TATASTEEL.NS","JSWSTEEL.NS","HINDALCO.NS",
        "SUNPHARMA.NS","DRREDDY.NS","CIPLA.NS","ULTRACEMCO.NS",
        "POWERGRID.NS","NTPC.NS","ONGC.NS","ADANIPORTS.NS",
        "ADANIENT.NS","BAJFINANCE.NS","BAJAJFINSV.NS","HEROMOTOCO.NS",
        "DIVISLAB.NS","BRITANNIA.NS","DABUR.NS","HDFCLIFE.NS",
        "SBILIFE.NS","TITAN.NS","EICHERMOT.NS","GRASIM.NS",
        "SHREECEM.NS","PIDILITIND.NS","AMBUJACEM.NS","ACC.NS",
        "ICICIPRULI.NS","ICICIGI.NS","BAJAJHLDNG.NS","MCDOWELL-N.NS"
    ]
}
